default_stages: [commit]
repos:
  - repo: https://github.com/yyang-even/yyLinuxConfig
    rev: e475e920fedb28f7bff2a58d1142a255fd3e86c4
    hooks:
      - id: shfmt

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
        stages: [commit]
